services:
    - type: web
      name: cms
      env: node
      plan: starter
      buildCommand: npm install && npm run build
      startCommand: npm run start
      healthCheckPath: /_health
      domains:
          - cms.financials.io
      disk:
          name: strapi-uploads
          mountPath: /opt/render/project/src/public/uploads
          sizeGB: 1
      envVars:
          - key: NODE_VERSION
            value: 14.15.1
          - key: NODE_ENV
            value: production
          - key: DATABASE_URL
            fromDatabase:
                name: strapi
                property: connectionString
          - key: JWT_SECRET
            generateValue: true
          - key: ADMIN_JWT_SECRET
            generateValue: true

databases:
    - name: strapi
      plan: starter
